- hosts: all
  remote_user: pi
  become_method: sudo
  name: "Restore Diario"
  tasks:
   - name: Unpack backup
     copy:
      src: backups/diario.sql
      dest: /home/pi
     
   - name: Restore SQL
     become: yes
     shell: docker-compose exec -T postgres psql -U postgres postgres < /home/pi/diario.sql
     args:
      chdir: /home/pi/diario
