[global]
template_dir = "templates/"
keep_alive = 5
limits = { forms = 32768 }
gmail_password = ""

[global.databases]
postgres_db = { url = "postgres://blog:blog@192.168.0.158/blog" }

[development]
address = "localhost"
port = 8000
log = "normal"
secret_key = "cZSiY8L2Tlpi9p+XEeAZ6f8uAIsJD5V3yXAuHGjojkk="


[staging]
address = "0.0.0.0"
port = 8000
log = "normal"
secret_key = "cZSiY8L2Tlpi9p+XEeAZ6f8uAIsJD5V3yXAuHGjojkk="

[production]
address = "0.0.0.0"
port = 6789
log = "critical"
